title: stratapp
short_title: stratapp
description: seamlessly execute strategy and day to day work in one place
baseurl:
url: https://stratapp.ai
permalink: "/:title/"
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  features:
    output: true
    permalink: "/features/:path/"
jekyll-archives:
  enabled: all
  layout: "archive"
gems:
  - jekyll-menus
  - jekyll-feed
  - jekyll-sitemap
plugins:
  - jekyll-sitemap
